name: qr_code_demo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  uuid: ^4.0.0
  get_it: ^7.6.0
  flutter_svg: ^2.0.7
  dotted_border: ^2.0.0+3
  stream_transform: ^2.1.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  scrollable_positioned_list: ^0.3.8
  permission_handler: ^10.4.3
  path_provider: ^2.1.1
  flutter_image_compress: ^2.0.4
  dotted_line: ^3.2.2
  share_plus: ^6.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
